// src/web-react/hotel-booker/src/components/toolbar/Toolbar.jsx
import { useNavigate } from "react-router-dom";
import "./Toolbar.css";

export default function Toolbar() {
    const navigate = useNavigate();

    return <div className="toolbar-container">
        <div className="toolbar-left">
            <span className="title" onClick={() => navigate('/')}>Hotel Booker</span>
        </div>
        <div className="toolbar-right"></div>
    </div>
}

// src/web/hotel-booker/src/app/components/toolbar/toolbar.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-toolbar',
  templateUrl: './toolbar.component.html',
  styleUrls: ['./toolbar.component.scss']
})
export class ToolbarComponent {
  constructor(private router: Router) { }
  titleClicked(): void {
    this.router.navigateByUrl('');
  }
}

<mat-toolbar>
    <div class = "left">
        <a (click)="titleClicked()" class="title">Hotel Booker</a>
    </div>
    <div class="right">
        <app-account-menu/>
    </div>
</mat-toolbar>
